### ISSUE TITLE
Why BPX discord channel was deleted ???

### ISSUE THREAD

**Issue by jmz-bit** [bpx-network/bpx-beacon-client#4]
Why BPX discord channel was deleted ???

What support channel are you providing now ???

**Comment by bpx-chain** [comment]
Hello,
We have decided to discontinue our activity on Discord and the official BPX discord server has been closed. We have nothing against creating an unofficial server, if someone is interested to maintain it. BPX is open source software provided "as is", for free and without any warranty. We are not going to provide any support in individual cases. GitHub Issues can be used for reporting bugs in our software. Any further updates on the project will be posted on our website and Twitter. Shutting down our Discord server does not have the slighest impact on the further development of this project. The project will be constantly developed without any doubt.
